{"name": "test_2_2", "status": "failed", "statusDetails": {"message": "AssertionError: assert (1 + 1) == 3", "trace": "self = <test_2.Tests object at 0x000001D0C03DB390>\n\n    @allure.description(\"Test #2.2\")\n    def test_2_2(self):\n>       assert 1+1==3\nE       assert (1 + 1) == 3\n\ntest\\test_2.py:12: AssertionError"}, "description": "Test #2.2", "start": 1672991452026, "stop": 1672991452026, "uuid": "4194e8d4-4125-460a-a2ba-1ae2563f46cb", "historyId": "2c37cd11368b728d3f2c5ec37b736fac", "testCaseId": "6c94ca8778194b7b23510600e710bba6", "fullName": "test.test_2.Tests#test_2_2", "labels": [{"name": "parentSuite", "value": "test"}, {"name": "suite", "value": "test_2"}, {"name": "subSuite", "value": "Tests"}, {"name": "host", "value": "LAPTOP-OE0K30SN"}, {"name": "thread", "value": "8036-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test.test_2"}]}